// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/demo/CustomerDemo.tsx": () => import("../components/mockups/demo/CustomerDemo.tsx"),
  "./components/mockups/landing-variants/VariantA.tsx": () => import("../components/mockups/landing-variants/VariantA.tsx"),
  "./components/mockups/landing-variants/VariantB.tsx": () => import("../components/mockups/landing-variants/VariantB.tsx")
};
